# Generated by Django 3.2.11 on 2022-07-19 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0003_alter_transfers_personnel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfers',
            old_name='proposed_appointment',
            new_name='proposed_appointment',
        ),
    ]
